// friendsStore.ts — Data access layer for the Friends feature.
// Each function issues the Supabase query and returns typed data.
// Business logic beyond what RLS enforces (rate-limiting, block checks,
// notification fan-out, etc.) is left for sessions F2+.
//
// NOTE: The Supabase typed client (`createClient<Database>`) does not yet
// resolve the social tables via generics because they were added to `database.ts`
// manually rather than auto-generated by the Supabase CLI.  The correct fix
// is to run `npx supabase gen types typescript` once the migrations are applied
// to your project, which will replace `database.ts` with a generated file that
// the client resolves correctly.  Until then, `db` below is cast to `any` so
// queries compile; all results are explicitly typed via the Db* interfaces.

import { supabase } from '@/lib/supabase'

// eslint-disable-next-line @typescript-eslint/no-explicit-any
const db = supabase as any

import {
  dbProfileToProfile,
  dbFriendRequestToFriendRequest,
  dbGameTagToGameTag,
  dbGameReactionToGameReaction,
  dbGameCommentToGameComment,
  dbNotificationToNotification,
  type UserProfile,
  type FriendRequest,
  type GameTag,
  type GameReaction,
  type GameComment,
  type DiaryNotification,
  type DbUserProfile,
  type DbFriendRequest,
  type DbGameTag,
  type DbGameReaction,
  type DbGameComment,
  type DbNotification,
} from '@/types/database'

// ─── Helpers ──────────────────────────────────────────────────────────────────

function throwOnError(error: unknown, context: string): void {
  if (error) throw new Error(`[friendsStore] ${context}: ${(error as Error).message}`)
}

// ─── Profile ─────────────────────────────────────────────────────────────────

export async function getMyProfile(): Promise<UserProfile> {
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) throw new Error('[friendsStore] getMyProfile: not authenticated')

  const { data, error } = await db
    .from('user_profiles')
    .select('*')
    .eq('user_id', user.id)
    .single()

  throwOnError(error, 'getMyProfile')
  return dbProfileToProfile(data as DbUserProfile)
}

export async function getUserProfile(userId: string): Promise<UserProfile | null> {
  const { data, error } = await db
    .from('user_profiles')
    .select('*')
    .eq('user_id', userId)
    .maybeSingle()

  throwOnError(error, 'getUserProfile')
  return data ? dbProfileToProfile(data as DbUserProfile) : null
}

export async function updateMyProfile(
  updates: Partial<Pick<UserProfile,
    | 'username' | 'displayName' | 'bio' | 'profilePhotoUrl'
    | 'isDiscoverableByUsername' | 'isDiscoverableByEmail'
    | 'isDiscoverableByShareCode' | 'privacyMode'
  >>
): Promise<UserProfile> {
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) throw new Error('[friendsStore] updateMyProfile: not authenticated')

  const payload: {
    username?: string | null
    display_name?: string | null
    bio?: string | null
    profile_photo_url?: string | null
    is_discoverable_by_username?: boolean
    is_discoverable_by_email?: boolean
    is_discoverable_by_share_code?: boolean
    privacy_mode?: boolean
  } = {}

  if (updates.username              !== undefined) payload.username                        = updates.username
  if (updates.displayName           !== undefined) payload.display_name                   = updates.displayName
  if (updates.bio                   !== undefined) payload.bio                             = updates.bio
  if (updates.profilePhotoUrl       !== undefined) payload.profile_photo_url              = updates.profilePhotoUrl
  if (updates.isDiscoverableByUsername  !== undefined) payload.is_discoverable_by_username  = updates.isDiscoverableByUsername
  if (updates.isDiscoverableByEmail     !== undefined) payload.is_discoverable_by_email     = updates.isDiscoverableByEmail
  if (updates.isDiscoverableByShareCode !== undefined) payload.is_discoverable_by_share_code = updates.isDiscoverableByShareCode
  if (updates.privacyMode           !== undefined) payload.privacy_mode                   = updates.privacyMode

  const { data, error } = await db
    .from('user_profiles')
    .update(payload)
    .eq('user_id', user.id)
    .select()
    .single()

  throwOnError(error, 'updateMyProfile')
  return dbProfileToProfile(data as DbUserProfile)
}

export async function findUserByUsername(username: string): Promise<UserProfile | null> {
  const { data, error } = await db
    .from('user_profiles')
    .select('*')
    .ilike('username', username)
    .eq('is_discoverable_by_username', true)
    .maybeSingle()

  throwOnError(error, 'findUserByUsername')
  return data ? dbProfileToProfile(data as DbUserProfile) : null
}

export async function findUserByEmail(_email: string): Promise<UserProfile | null> {
  // TODO (F3): requires a Supabase edge function — auth.users.email is not
  // accessible to the anon/authenticated role directly.
  console.warn('[friendsStore] findUserByEmail: not yet implemented')
  return null
}

export async function findUserByShareCode(shareCode: string): Promise<UserProfile | null> {
  const { data, error } = await db
    .from('user_profiles')
    .select('*')
    .eq('share_code', shareCode.toUpperCase())
    .eq('is_discoverable_by_share_code', true)
    .maybeSingle()

  throwOnError(error, 'findUserByShareCode')
  return data ? dbProfileToProfile(data as DbUserProfile) : null
}

// ─── Friend requests ──────────────────────────────────────────────────────────

export async function sendFriendRequest(toUserId: string): Promise<FriendRequest> {
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) throw new Error('[friendsStore] sendFriendRequest: not authenticated')

  // TODO (F4): check that the target user hasn't blocked the sender
  // TODO (F4): check that a pending request doesn't already exist in either direction

  const { data, error } = await db
    .from('friend_requests')
    .insert({ from_user_id: user.id, to_user_id: toUserId, status: 'pending' })
    .select()
    .single()

  throwOnError(error, 'sendFriendRequest')
  const req = dbFriendRequestToFriendRequest(data as DbFriendRequest)

  // Notify the recipient
  await db.from('notifications').insert({
    user_id: toUserId,
    type: 'friend_request',
    actor_user_id: user.id,
    subject_id: req.id,
    subject_type: 'friend_request',
  })

  return req
}

export async function acceptFriendRequest(requestId: string): Promise<void> {
  // Uses the SECURITY DEFINER RPC from migration 006 which atomically:
  // creates the friendship row, updates request status, and notifies the sender.
  const { error } = await db.rpc('accept_friend_request', { request_id: requestId })
  throwOnError(error, 'acceptFriendRequest')
}

export async function denyFriendRequest(requestId: string): Promise<void> {
  const { error } = await db
    .from('friend_requests')
    .update({ status: 'denied', responded_at: new Date().toISOString() })
    .eq('id', requestId)

  throwOnError(error, 'denyFriendRequest')
}

export async function cancelFriendRequest(requestId: string): Promise<void> {
  const { error } = await db
    .from('friend_requests')
    .update({ status: 'cancelled', responded_at: new Date().toISOString() })
    .eq('id', requestId)

  throwOnError(error, 'cancelFriendRequest')
}

export async function listIncomingRequests(): Promise<FriendRequest[]> {
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return []

  const { data, error } = await db
    .from('friend_requests')
    .select('*')
    .eq('to_user_id', user.id)
    .eq('status', 'pending')
    .order('created_at', { ascending: false })

  throwOnError(error, 'listIncomingRequests')
  return ((data ?? []) as DbFriendRequest[]).map(dbFriendRequestToFriendRequest)
}

export async function listOutgoingRequests(): Promise<FriendRequest[]> {
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return []

  const { data, error } = await db
    .from('friend_requests')
    .select('*')
    .eq('from_user_id', user.id)
    .eq('status', 'pending')
    .order('created_at', { ascending: false })

  throwOnError(error, 'listOutgoingRequests')
  return ((data ?? []) as DbFriendRequest[]).map(dbFriendRequestToFriendRequest)
}

// ─── Friends ──────────────────────────────────────────────────────────────────

export async function listMyFriends(): Promise<UserProfile[]> {
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return []

  const { data: friendships, error } = await db
    .from('friendships')
    .select('*')
    .or(`user_a_id.eq.${user.id},user_b_id.eq.${user.id}`)

  throwOnError(error, 'listMyFriends')
  if (!friendships?.length) return []

  const friendIds = (friendships as { user_a_id: string; user_b_id: string }[]).map((f) =>
    f.user_a_id === user.id ? f.user_b_id : f.user_a_id
  )

  const { data: profiles, error: pErr } = await db
    .from('user_profiles')
    .select('*')
    .in('user_id', friendIds)

  throwOnError(pErr, 'listMyFriends (profiles)')
  return ((profiles ?? []) as DbUserProfile[]).map(dbProfileToProfile)
}

export async function listMutualFriends(otherUserId: string): Promise<UserProfile[]> {
  // TODO (F5): implement server-side via Supabase RPC for efficiency.
  // Stub: fetch both friend lists and intersect in the app layer.
  const [myFriends, theirProfiles] = await Promise.all([
    listMyFriends(),
    (async () => {
      const { data: fs, error } = await db
        .from('friendships')
        .select('*')
        .or(`user_a_id.eq.${otherUserId},user_b_id.eq.${otherUserId}`)

      if (error) return []
      const ids = ((fs ?? []) as { user_a_id: string; user_b_id: string }[]).map((f) =>
        f.user_a_id === otherUserId ? f.user_b_id : f.user_a_id
      )
      if (!ids.length) return []

      const { data: profiles } = await db
        .from('user_profiles')
        .select('*')
        .in('user_id', ids)

      return ((profiles ?? []) as DbUserProfile[]).map(dbProfileToProfile)
    })(),
  ])

  const myFriendIds = new Set(myFriends.map((p) => p.userId))
  return theirProfiles.filter((p) => myFriendIds.has(p.userId))
}

export async function removeFriend(friendUserId: string): Promise<void> {
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) throw new Error('[friendsStore] removeFriend: not authenticated')

  const userA = user.id < friendUserId ? user.id : friendUserId
  const userB = user.id < friendUserId ? friendUserId : user.id

  const { error } = await db
    .from('friendships')
    .delete()
    .eq('user_a_id', userA)
    .eq('user_b_id', userB)

  throwOnError(error, 'removeFriend')
}

export async function areFriends(otherUserId: string): Promise<boolean> {
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return false

  const userA = user.id < otherUserId ? user.id : otherUserId
  const userB = user.id < otherUserId ? otherUserId : user.id

  const { data, error } = await db
    .from('friendships')
    .select('id')
    .eq('user_a_id', userA)
    .eq('user_b_id', userB)
    .maybeSingle()

  throwOnError(error, 'areFriends')
  return data !== null
}

// ─── Block & mute ─────────────────────────────────────────────────────────────

export async function blockUser(userId: string): Promise<void> {
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) throw new Error('[friendsStore] blockUser: not authenticated')

  // TODO (F6): also remove any existing friendship and pending requests
  const { error } = await db
    .from('blocked_users')
    .insert({ blocker_user_id: user.id, blocked_user_id: userId })

  throwOnError(error, 'blockUser')
}

export async function unblockUser(userId: string): Promise<void> {
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) throw new Error('[friendsStore] unblockUser: not authenticated')

  const { error } = await db
    .from('blocked_users')
    .delete()
    .eq('blocker_user_id', user.id)
    .eq('blocked_user_id', userId)

  throwOnError(error, 'unblockUser')
}

export async function listBlockedUsers(): Promise<UserProfile[]> {
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return []

  const { data: blocks, error } = await db
    .from('blocked_users')
    .select('*')
    .eq('blocker_user_id', user.id)

  throwOnError(error, 'listBlockedUsers')
  if (!blocks?.length) return []

  const ids = (blocks as { blocked_user_id: string }[]).map((b) => b.blocked_user_id)
  const { data: profiles, error: pErr } = await db
    .from('user_profiles')
    .select('*')
    .in('user_id', ids)

  throwOnError(pErr, 'listBlockedUsers (profiles)')
  return ((profiles ?? []) as DbUserProfile[]).map(dbProfileToProfile)
}

export async function muteUser(userId: string): Promise<void> {
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) throw new Error('[friendsStore] muteUser: not authenticated')

  const { error } = await db
    .from('muted_users')
    .insert({ muter_user_id: user.id, muted_user_id: userId })

  throwOnError(error, 'muteUser')
}

export async function unmuteUser(userId: string): Promise<void> {
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) throw new Error('[friendsStore] unmuteUser: not authenticated')

  const { error } = await db
    .from('muted_users')
    .delete()
    .eq('muter_user_id', user.id)
    .eq('muted_user_id', userId)

  throwOnError(error, 'unmuteUser')
}

export async function listMutedUsers(): Promise<UserProfile[]> {
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return []

  const { data: mutes, error } = await db
    .from('muted_users')
    .select('*')
    .eq('muter_user_id', user.id)

  throwOnError(error, 'listMutedUsers')
  if (!mutes?.length) return []

  const ids = (mutes as { muted_user_id: string }[]).map((m) => m.muted_user_id)
  const { data: profiles, error: pErr } = await db
    .from('user_profiles')
    .select('*')
    .in('user_id', ids)

  throwOnError(pErr, 'listMutedUsers (profiles)')
  return ((profiles ?? []) as DbUserProfile[]).map(dbProfileToProfile)
}

// ─── Game social actions ───────────────────────────────────────────────────────
// These are stubs used by sessions F7 (reactions/comments) and F8 (tags).

export async function addReaction(gameId: string, emoji: string): Promise<GameReaction> {
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) throw new Error('[friendsStore] addReaction: not authenticated')

  const { data, error } = await db
    .from('game_reactions')
    .insert({ game_id: gameId, user_id: user.id, emoji })
    .select()
    .single()

  throwOnError(error, 'addReaction')
  return dbGameReactionToGameReaction(data as DbGameReaction)
}

export async function removeReaction(gameId: string, emoji: string): Promise<void> {
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) throw new Error('[friendsStore] removeReaction: not authenticated')

  const { error } = await db
    .from('game_reactions')
    .delete()
    .eq('game_id', gameId)
    .eq('user_id', user.id)
    .eq('emoji', emoji)

  throwOnError(error, 'removeReaction')
}

export async function listReactions(gameId: string): Promise<GameReaction[]> {
  const { data, error } = await db
    .from('game_reactions')
    .select('*')
    .eq('game_id', gameId)
    .order('created_at')

  throwOnError(error, 'listReactions')
  return ((data ?? []) as DbGameReaction[]).map(dbGameReactionToGameReaction)
}

export async function addComment(
  gameId: string,
  content: string,
  parentCommentId?: string,
): Promise<GameComment> {
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) throw new Error('[friendsStore] addComment: not authenticated')

  const { data, error } = await db
    .from('game_comments')
    .insert({
      game_id: gameId,
      user_id: user.id,
      content,
      parent_comment_id: parentCommentId ?? null,
    })
    .select()
    .single()

  throwOnError(error, 'addComment')
  return dbGameCommentToGameComment(data as DbGameComment)
}

export async function deleteComment(commentId: string): Promise<void> {
  const { error } = await db
    .from('game_comments')
    .delete()
    .eq('id', commentId)

  throwOnError(error, 'deleteComment')
}

export async function listComments(gameId: string): Promise<GameComment[]> {
  const { data, error } = await db
    .from('game_comments')
    .select('*')
    .eq('game_id', gameId)
    .order('created_at')

  throwOnError(error, 'listComments')
  return ((data ?? []) as DbGameComment[]).map(dbGameCommentToGameComment)
}

export async function tagUser(gameId: string, taggedUserId: string): Promise<GameTag> {
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) throw new Error('[friendsStore] tagUser: not authenticated')

  // TODO (F8): notify the tagged user
  const { data, error } = await db
    .from('game_tags')
    .insert({ game_id: gameId, tagged_user_id: taggedUserId, tagged_by_user_id: user.id })
    .select()
    .single()

  throwOnError(error, 'tagUser')
  return dbGameTagToGameTag(data as DbGameTag)
}

export async function removeTag(gameId: string, taggedUserId: string): Promise<void> {
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) throw new Error('[friendsStore] removeTag: not authenticated')

  if (taggedUserId === user.id) {
    // Tagged user removes themselves — set flag rather than delete row.
    const { error } = await db
      .from('game_tags')
      .update({ removed_by_tagged_user: true })
      .eq('game_id', gameId)
      .eq('tagged_user_id', user.id)
    throwOnError(error, 'removeTag (self)')
  } else {
    // Game owner deletes the tag row entirely.
    const { error } = await db
      .from('game_tags')
      .delete()
      .eq('game_id', gameId)
      .eq('tagged_user_id', taggedUserId)
    throwOnError(error, 'removeTag (owner)')
  }
}

export async function listTags(gameId: string): Promise<GameTag[]> {
  const { data, error } = await db
    .from('game_tags')
    .select('*')
    .eq('game_id', gameId)
    .eq('removed_by_tagged_user', false)

  throwOnError(error, 'listTags')
  return ((data ?? []) as DbGameTag[]).map(dbGameTagToGameTag)
}

// ─── Notifications ────────────────────────────────────────────────────────────

export async function listNotifications(limit = 50): Promise<DiaryNotification[]> {
  const { data, error } = await db
    .from('notifications')
    .select('*')
    .order('created_at', { ascending: false })
    .limit(limit)

  throwOnError(error, 'listNotifications')
  return ((data ?? []) as DbNotification[]).map(dbNotificationToNotification)
}

export async function markNotificationRead(notificationId: string): Promise<void> {
  const { error } = await db
    .from('notifications')
    .update({ read: true })
    .eq('id', notificationId)

  throwOnError(error, 'markNotificationRead')
}

export async function markAllNotificationsRead(): Promise<void> {
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return

  const { error } = await db
    .from('notifications')
    .update({ read: true })
    .eq('user_id', user.id)
    .eq('read', false)

  throwOnError(error, 'markAllNotificationsRead')
}

export async function unreadNotificationCount(): Promise<number> {
  const { count, error } = await db
    .from('notifications')
    .select('*', { count: 'exact', head: true })
    .eq('read', false)

  throwOnError(error, 'unreadNotificationCount')
  return count ?? 0
}

// ─── Discovery ────────────────────────────────────────────────────────────────

// Partial username search — multiple results.
// Filters: is_discoverable_by_username=true, privacy_mode=false, not self.
// Note: users who have blocked the caller may still appear here because the
// blocked_users RLS only exposes the blocker's own rows. Blocked IDs should be
// filtered client-side using getMyBlockedIds().
export async function searchByUsername(query: string): Promise<UserProfile[]> {
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return []

  const { data, error } = await db
    .from('user_profiles')
    .select('*')
    .ilike('username', `%${query}%`)
    .eq('is_discoverable_by_username', true)
    .eq('privacy_mode', false)
    .neq('user_id', user.id)
    .limit(10)

  throwOnError(error, 'searchByUsername')
  return ((data ?? []) as DbUserProfile[]).map(dbProfileToProfile)
}

// Returns the IDs of users the current user has blocked (for client-side filtering).
export async function getMyBlockedIds(): Promise<string[]> {
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return []

  const { data } = await db
    .from('blocked_users')
    .select('blocked_user_id')
    .eq('blocker_user_id', user.id)

  return ((data ?? []) as { blocked_user_id: string }[]).map(b => b.blocked_user_id)
}

export interface FriendSuggestion {
  profile: UserProfile
  mutualCount: number
  sampleMutuals: UserProfile[]
}

// Friend-of-friend suggestions sorted by mutual friend count.
// Does NOT filter by discovery flags (socially-trusted channel), but DOES
// respect privacy_mode (the master kill switch per spec).
export async function getFriendSuggestions(): Promise<FriendSuggestion[]> {
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return []

  // My current friendships
  const { data: myFriendships } = await db
    .from('friendships')
    .select('user_a_id,user_b_id')
    .or(`user_a_id.eq.${user.id},user_b_id.eq.${user.id}`)

  const myFriendIds: string[] = (
    (myFriendships ?? []) as { user_a_id: string; user_b_id: string }[]
  ).map(f => (f.user_a_id === user.id ? f.user_b_id : f.user_a_id))

  if (!myFriendIds.length) return []

  // IDs I've blocked (to exclude from suggestions)
  const { data: blockedData } = await db
    .from('blocked_users')
    .select('blocked_user_id')
    .eq('blocker_user_id', user.id)
  const blockedIdSet = new Set(
    ((blockedData ?? []) as { blocked_user_id: string }[]).map(b => b.blocked_user_id)
  )

  // Friendships of MY friends (cap at 50 for query sanity)
  const queryFriendIds = myFriendIds.slice(0, 50)
  const { data: fofFriendships } = await db
    .from('friendships')
    .select('user_a_id,user_b_id')
    .or(`user_a_id.in.(${queryFriendIds.join(',')}),user_b_id.in.(${queryFriendIds.join(',')})`)

  const myFriendIdSet = new Set(myFriendIds)
  const fofCounts = new Map<string, number>()
  const fofMutualSets = new Map<string, Set<string>>()

  for (const f of ((fofFriendships ?? []) as { user_a_id: string; user_b_id: string }[])) {
    const isAMyFriend = myFriendIdSet.has(f.user_a_id)
    const friendId = isAMyFriend ? f.user_a_id : f.user_b_id
    const fofId = isAMyFriend ? f.user_b_id : f.user_a_id

    if (fofId === user.id) continue
    if (myFriendIdSet.has(fofId)) continue
    if (blockedIdSet.has(fofId)) continue

    fofCounts.set(fofId, (fofCounts.get(fofId) ?? 0) + 1)
    if (!fofMutualSets.has(fofId)) fofMutualSets.set(fofId, new Set())
    fofMutualSets.get(fofId)!.add(friendId)
  }

  const sorted = [...fofCounts.entries()].sort((a, b) => b[1] - a[1]).slice(0, 10)
  if (!sorted.length) return []

  const fofIds = sorted.map(([id]) => id)
  const allMutualIds = [...new Set([...fofMutualSets.values()].flatMap(s => [...s]))]

  // Fetch profiles — exclude privacy_mode users (master kill switch)
  const [profilesRes, mutualsRes] = await Promise.all([
    db.from('user_profiles').select('*').in('user_id', fofIds).eq('privacy_mode', false),
    allMutualIds.length
      ? db.from('user_profiles').select('user_id,display_name,username,profile_photo_url').in('user_id', allMutualIds)
      : Promise.resolve({ data: [] }),
  ])

  const profileMap = new Map(
    ((profilesRes.data ?? []) as DbUserProfile[]).map(p => [p.user_id, dbProfileToProfile(p)])
  )
  const mutualMap = new Map(
    ((mutualsRes.data ?? []) as DbUserProfile[]).map(p => [p.user_id, dbProfileToProfile(p)])
  )

  return sorted
    .map(([fofId, mutualCount]) => {
      const profile = profileMap.get(fofId)
      if (!profile) return null // filtered by privacy_mode
      const mutualIds = [...(fofMutualSets.get(fofId) ?? [])]
      const sampleMutuals = mutualIds
        .slice(0, 3)
        .map(id => mutualMap.get(id))
        .filter((p): p is UserProfile => p !== undefined)
      return { profile, mutualCount, sampleMutuals }
    })
    .filter((x): x is FriendSuggestion => x !== null)
}
